import re
import time
from typing import Any, Dict, List, Optional, Tuple, Union

from autopilot.data import (
  ContextData,
  ExtraInfo,
  MessageType,
  RedirectedOutputExtraInfo,
  WorkflowConfig,
)
from autopilot.terminal._utils import cp_to_container
from autopilot.terminal.term import Term
from autopilot.utils import extract_commands

from .base import BaseNode, NodeOutputType, Role

keystroke_pattern = re.compile(
  r"""
        ^(                          # Start of string anchor
            (?:                     # Non-capturing group for optional modifier + key
                (?:ctrl|control|alt|shift|super)\+  # Modifiers (optional)
            )?
            (?:                    # Actual key options
                f[1-9]            # Function keys f1-f9
                |f1[0-2]           # Function keys f10-f12
                |enter|escape|esc|tab|backspace|delete|space  # Named special keys
                |up|down|left|right|home|end|pageup|pagedown  # Arrow and navigation keys
                |[a-zA-Z0-9]            # Single alphanumeric key
                |[.,;'\[\]\-=/`~!@#$%^&*()_+{}|:"<>?\\]  # Special characters
            )
        )                           # End of capture
    """,
  re.VERBOSE,
)


def match_keystrokes(content: str) -> List[str]:
  """
  Match the keystrokes from the content.

  Args:
    content (str): the content to match the keystrokes

  Returns:
    keystrokes (List[str]): the keystrokes matched from the content
  """
  keystrokes = []
  for line in content.splitlines():
    line_ = line
    while line_:
      match = keystroke_pattern.match(line_)
      if not match:
        raise ValueError(f"""keystroke format error: {line},
you can enter one key at a line, keys with modifier like "ctrl+c", \
single key like "a", special key like "escape", "enter".""")
      keystrokes.append(match.group(1))
      line_ = line_[len(match.group(1)) :]
  return keystrokes


class TerminalNode(BaseNode):
  """
  TerminalNode executes the command generated by the LLM and returns the output.

  Args:
    terminal (Term): the terminal to use for the workflow.
  """

  terminal: Term  # type: ignore[assignment]

  def __init__(self, terminal: Term, workflow_config: WorkflowConfig):
    super().__init__("terminal", Role.USER, workflow_config, terminal)
    self.terminal = terminal
    self.output_node: Optional[BaseNode] = None

  def _exec_and_return_output(self, cmd_type: str, cmd: str) -> str:
    """
    Execute the command and return the output.

    Args:
        cmd_type (str): the type of the command
        cmd (str): the command to execute

    Returns:
        output (str): the output of the command
    """
    cmd_lines = cmd.splitlines()

    if cmd_type == "key":
      self.terminal.save_old_text()
      try:
        keys = match_keystrokes(cmd)
      except ValueError as e:
        error_text = f"KeyError: {e}"
        return error_text
      for key in keys:
        self.console.print(f"sending key {key}", message_type=MessageType.LOG)
        self.terminal.send_key(key)
    else:
      if len(cmd_lines) == 1:
        self.terminal.send_text(cmd_lines[0], paste=False)
      else:  # multiline
        self.terminal.send_text(cmd + "\n", paste=True)
      self.terminal.save_old_text()
      self.terminal.send_key("enter")
    time.sleep(0.1)
    # wait for the terminal to be ready to avoid race condition.
    # Otherwise, self.terminal.wait() will be triggered immediately even though the command is not executed.
    timeout = self.terminal.wait()
    text: str
    if timeout:
      text = self.get_terminal_text(screen=True)
    else:
      text = self.get_terminal_text()
    return text

  def set_output_nodes(self, node: BaseNode) -> None:
    self.output_node = node

  def _handle_long_output(
    self, output: str, cmd: str, data: ContextData
  ) -> NodeOutputType:
    """Handle long output by writing to a temporary file."""
    import os
    import tempfile

    self.console.print(
      "[bold green]Output is too long, writing to file[/bold green]",
      message_type=MessageType.LOG,
    )

    # Create temporary file
    with tempfile.NamedTemporaryFile(
      mode="w", delete=False, suffix=".txt"
    ) as f:
      f.write(output)
      temp_file = f.name

    try:
      # Determine file path based on sandbox configuration
      if self.workflow_config.sandbox:
        container_path = "/tmp/terminal_output.txt"
        cp_to_container(self.workflow_config.sandbox, temp_file, container_path)
        file_path = container_path
      else:
        file_path = temp_file

      # Create extra info for LLM
      extra_info_to_llm = (
        f"Workflow: The result of running `{cmd}` is excessively long, so it has been written to `{file_path}`. "
        "File may be extremely large. Avoid `cat` unless necessary and definitely don't use `less`/`top`/`vim` to view the file. \n\n"
      )
      self.append_and_print(self.role, self.name, f"{cmd} >> {file_path}", data)

      return self.output_node, RedirectedOutputExtraInfo(
        output=extra_info_to_llm
      )

    except Exception as e:
      self.console.print(
        f"[bold red]Error writing output to file: {e}[/bold red]",
        message_type=MessageType.ERROR,
      )
      # Fallback: truncate and display output
      truncated_output = (
        f"{output[:100]}\n... (output truncated)\n{output[-100:]}"
      )
      self.append_and_print(self.role, self.name, truncated_output, data)
      return self.output_node, None

    finally:
      # Clean up temporary file
      try:
        os.unlink(temp_file)
      except OSError:
        pass

  def run(  # type: ignore[override]
    self, data: ContextData, extra_info: Optional[ExtraInfo] = None
  ) -> NodeOutputType:
    # get the last output
    last_message = data.last_message
    if last_message is None:
      raise ValueError("No last message found")
    assert last_message.role == Role.LLM, (
      f"Invalid role: {last_message.role} found in the last message for the terminal node"
    )
    commands = extract_commands(last_message.content)
    cmd_type, cmd = commands[0]
    try:
      output = self._exec_and_return_output(cmd_type, cmd)
    except Exception as e:
      # interrupt the execution
      self.console.print(
        f"[bold red]Error: {e}[/bold red]", message_type=MessageType.ERROR
      )
      return None, None

    # Handle long output by writing to file
    if (
      self.workflow_config.strong_scaffold
      and len(output) > 5000
      and "/tmp/terminal_output.txt" not in cmd
    ):
      return self._handle_long_output(output, cmd, data)

    # Handle TUI timeout (agent cannot exit the TUI)
    if self.workflow_config.strong_scaffold and self.terminal.tui_timeout:
      extra_info_to_llm = (
        "Workflow: The agent has been stuck in the TUI. "
        "It should not use TUI-related cmds like `vim`, `less`, etc."
      )
      self.append_and_print(self.role, self.name, output, data)
      return self.output_node, RedirectedOutputExtraInfo(
        output=extra_info_to_llm
      )

    # Handle terminal timeout (command takes too long)
    if self.workflow_config.strong_scaffold and self.terminal.terminal_timeout:
      extra_info_to_llm = (
        f"Workflow: The command `{cmd}` took too long to execute and timed out. "
        "It might be waiting for input, running indefinitely, or experiencing issues. "
        "Consider breaking it into smaller commands or using non-interactive alternatives."
      )
      self.append_and_print(self.role, self.name, output, data)
      return self.output_node, RedirectedOutputExtraInfo(
        output=extra_info_to_llm
      )

    self.append_and_print(self.role, self.name, output, data)
    return self.output_node, None
