import os
import re
import tempfile
from threading import Event
from typing import Any, Dict, Optional, Tuple

from pydantic import Extra

from autopilot.data import (
  ContextData,
  DirectActionExtraInfo,
  EditExtraInfo,
  ExtraInfo,
  InteractionMode,
  Message,
  MessageType,
  WorkflowConfig,
)
from autopilot.terminal.term import Term
from autopilot.utils import extract_commands

from .base import BaseNode, NodeOutputType, Role
from .llm_node import LLMNode
from .terminal_node import TerminalNode


class UserActionNode(BaseNode):
  """
  UserActionNode is the node that allows the user to take an action including proceed, feedback and edit.

  Args:
    event (Event): the event to interrupt the user action
    terminal (Term): the terminal to use for the workflow
  """

  def __init__(
    self, event: Event, terminal: Term, workflow_config: WorkflowConfig
  ):
    super().__init__("user-action", Role.USER, workflow_config, terminal)
    self.llm_node: Optional[LLMNode] = None
    self.terminal_node: Optional[TerminalNode] = None
    self.event = event
    self.editor = os.getenv("EDITOR", "vim")

  def set_output_nodes(
    self, llm_node: LLMNode, terminal_node: TerminalNode
  ) -> None:
    assert isinstance(llm_node, LLMNode), (
      "llm_node must be an instance of LLMNode"
    )
    assert isinstance(terminal_node, TerminalNode), (
      "terminal_node must be an instance of TerminalNode"
    )
    self.llm_node = llm_node
    self.terminal_node = terminal_node

  def _user_input(self, data: ContextData) -> Tuple[str, int]:
    """
    Parse the user input as action and the target step.

    Args:
      data (ContextData): the context data

    Returns:
      action (str): the action to take
      target_step (int): the target step for the action
    """
    self.console.print(
      "[bold green]Proceed (p), feedback (f), edit (e), resample next one (n) or record (r).",
      message_type=MessageType.FORMATTING,
    )
    self.console.print(
      "[bold green]Optionally, you can add a step number after the command.",
      message_type=MessageType.FORMATTING,
    )
    while True:
      # match the user input for p, f and e
      user_input = self.console.prompt("([p]/f/e/n/r): ").strip().lower()
      user_input = user_input.lower().strip()
      # parse
      match = re.match(r"([pfenr]?)(.*)", user_input)

      try:
        action = match[1]  # type: ignore
        action = action or "p"
        step = match[2].strip()  # type: ignore
        step = -1 if step == "" else int(step)
      except Exception:
        self.console.print(
          f"[bold red]Invalid command: {user_input}",
          message_type=MessageType.FORMATTING,
        )
        continue

      # validate
      if step >= data.num_steps or step < -data.num_steps:
        self.console.print(
          f"[bold red]Step number {step} out of range. "
          "Please enter a step number in "
          f"[{-data.num_steps}, {data.num_steps}).",
          message_type=MessageType.WARNING,
        )
        continue

      # get the target message based on the step
      step_role = data.current_branch[step].role
      if action in ("e", "n") and step_role != Role.LLM:
        self.console.print(
          "[bold red]You can only edit or resample an LLM step, "
          f"step {step} is generated by {step_role}",
          message_type=MessageType.WARNING,
        )
        continue
      if action == "r" and step_role != Role.LLM:
        self.console.print(
          "[bold red]You can only record a turning point at an LLM step, "
          f"step {step} is generated by {step_role}",
          message_type=MessageType.WARNING,
        )
        continue

      # step starts from 0
      step = step if step >= 0 else data.num_steps + step
      self.event.clear()
      return action, step

  def _proceed(self, data: ContextData) -> NodeOutputType:
    """
    Proceed to the next step.

    Args:
      data (ContextData): the context data

    Returns:
      NodeOutputType: the next node and the extra info
    """
    # depending on the last step type, we either proceed
    # to the llm step or terminal step.
    last_message = data.last_message

    if last_message is None:
      raise ValueError("No last message found")

    if last_message.role == Role.LLM:
      # if the previous role is LLM we just pass the control to the terminal node
      commands = extract_commands(last_message.content)
      commands_history = data.cmd_history[:-1]
      if len(commands) == 0:
        if data.in_substack:
          result = re.findall(
            r"\[RESULT\](.*?)\[/RESULT\]", last_message.content, re.DOTALL
          )
          if len(result) > 0:
            data.close_substack()
            self.append_and_print(
              Role.USER, "user", "Subtask result:\n" + result[-1], data
            )
            return self.llm_node, None
        if (
          self.workflow_config.interaction_mode
          == InteractionMode.EXECUTIVE_ONLY
        ):
          if "all done" in last_message.content.lower():
            return None, None
          else:
            # if no 'all done' and no code block, we feedback a warning
            code_block_warning = (
              "Please ensure your output contains EXACTLY ONE fenced code block (e.g., ```shell\nls -lS\n```).\n"
              "Ensure proper code block formatting with line breaks at the end of each command.\n"
              'If you think the task is complete (analyse it step by step), respond with "the task is all done" without any code block.'
            )
            self.append_and_print(Role.USER, "user", code_block_warning, data)
            return self.llm_node, None
        else:
          text = self.get_terminal_text()
          if text != "## terminal:\n\n":
            self.append_and_print(Role.USER, "terminal", text, data)
            return self.llm_node, None
          else:
            self.console.print(
              "[bold yellow]Nothing to do.",
              message_type=MessageType.NO_COMMAND_FOUND,
            )
            return self, None
      elif len(commands) > 1:
        code_block_warning = "Please generate only ONE fenced code block at a time. Multiple code blocks are not allowed."
        self.append_and_print(Role.USER, "user", code_block_warning, data)
        return self.llm_node, None
      else:  # len(commands) == 1
        commands = extract_commands(last_message.content)
        cmd_type, cmd = commands[0]
        if cmd_type == "subtask":
          data.open_substack()
          extra_info = "\nWhen you finish, generate and surround the return information in [RESULT]...[/RESULT]."
          self.append_and_print(Role.USER, "user", cmd + extra_info, data)
          return self.llm_node, None
        elif cmd_type == "context":
          return self._execute_context_command(cmd, data)
        elif (
          self.workflow_config.strong_scaffold
          and len(commands_history) > 0
          and cmd == commands_history[-1]
        ):
          code_block_warning = (
            f"You have repeated the same command in the previous step: `{commands_history[-1]}`. "
            "It is harmful to repeat it without any changes. "
            "Please carefully think about your next command."
          )
          self.append_and_print(Role.USER, "user", code_block_warning, data)
          return self.llm_node, None
        elif "all done" in cmd or "all_done" in cmd:
          code_block_warning = "If you think the task is finished, just says `the task is all done.` and do not output any code block."
          self.append_and_print(Role.USER, "user", code_block_warning, data)
          return self.llm_node, None
        elif "exit" == cmd:
          code_block_warning = "Please do not use 'exit' command as it will break the workflow. To finish, say 'all done' without any code block."
          self.append_and_print(Role.USER, "user", code_block_warning, data)
          return self.llm_node, None
        else:
          return self.terminal_node, None
    elif last_message.role == Role.USER:
      return self.llm_node, None
    else:
      raise ValueError(
        f"Invalid role: {last_message.role} found in the last message for the proceed action"
      )

  def _edit(
    self, message: Message, data: ContextData, resample: bool = False
  ) -> NodeOutputType:
    """
    Edit the message.
    Args:
      message (Message): the message to edit
      data (ContextData): the context data
      resample (bool): whether to resample the message

    Returns:
      Tuple[Optional["BaseNode"], Optional[ExtraInfo]]: the next node and the extra info
    """
    name = None

    if (
      self.workflow_config.interaction_mode
      == InteractionMode.INTERACTIVE_BY_ZMQ
    ):
      new_content = self.console.prompt()
    elif resample:
      new_content = ""
    else:
      with tempfile.NamedTemporaryFile(
        mode="w+",
        delete=False,
        encoding="utf-8",
        prefix=f"edit-{message.step}-",
        suffix=".md",
      ) as f:
        f.write(message.content)
        f.flush()
        name = f.name
      os.system(f"{self.editor} {f.name}")
      with open(name, "rt") as file_handle:
        file_handle.seek(0)
        new_content = file_handle.read().rstrip(" \n\r")
      os.remove(name)

    # TODO (FrankLeeeee): fix the generation of the remaining content
    if new_content != message.content:
      data.branch_at(message.step - 1)
      extra_info = EditExtraInfo(
        edit_prefix=new_content, content_before_edit=message.content
      )
      if new_content.endswith("\neos"):
        new_content = new_content[:-4]
        self.append_and_print(
          message.role,
          message.name,
          new_content,
          data,
          title=f"# Step {message.step} (amend with EOS)",
        )
        return self, None
      else:
        return self.llm_node, extra_info
    else:
      self.append_and_print(Role.LLM, "llm", message.content, data)
      return self._proceed(data)

  def _feedback(self, data: ContextData) -> NodeOutputType:
    """
    Prompt the user for feedback and proceed to the next step.
    Args:
      data (ContextData): the context data

    Returns:
      Tuple[Optional["BaseNode"], Optional[ExtraInfo]]: the next node and the extra info
    """
    feedback = self.console.prompt("write your feedback: ")

    if feedback == "":
      return self._proceed(data)
    else:
      self.append_and_print(Role.USER, "user", feedback, data)
      return self.llm_node, None

  def _summarize(self, start_idx, end_idx, summary, data):
    # Summarize data.substack[start_idx:end_idx]

    # substack_top points to the current summarize command itself
    # end_idx cannot be greater than substack_top
    substack_top = len(data.substack) - 1

    def _validate_indices(s_id, e_id, s_len):
      valid_flag = (s_id < e_id) and (0 <= s_id < s_len) and (0 < e_id <= s_len)
      return valid_flag

    if start_idx >= end_idx:
      raise ValueError(
        f"Start index must be less than end index, got {start_idx} >= {end_idx}"
      )
    message = ""
    # Fixable checks
    if start_idx < 0 or start_idx >= substack_top:
      raise ValueError(
        f"Start index {start_idx} out of range, must be in 0 <= start_idx < {substack_top}."
      )
    if end_idx <= 0 or end_idx > substack_top:
      if end_idx <= 0:
        raise ValueError(
          f"End index {end_idx} out of range, must be in 0 < end_idx <= {substack_top}."
        )
      else:
        old_end_idx = end_idx
        end_idx = max(1, min(end_idx, substack_top))
        message += f"End index {old_end_idx} out of range, must be in 0 < end_idx <= {substack_top}. Adjusted to {end_idx}.\n"

      assert _validate_indices(start_idx, end_idx, substack_top), (
        f"{message}Invalid indices after adjustment: start_idx={start_idx}, end_idx={end_idx}, substack_top={substack_top}. "
        "Ensure 0 <= start_idx < end_idx <= substack_top."
      )

    # map to absolute indices
    start_idx = start_idx + data.substack_bottom
    end_idx = end_idx + data.substack_bottom

    # Check if start_idx and end_idx satisfy LLM-User alternation
    # start_idx role should be LLM, end_idx role should be USER
    if (
      data.current_branch[start_idx].role != Role.LLM
      or data.current_branch[end_idx - 1].role != Role.USER
    ):
      message += (
        f"The context to summarize must start with an {Role.LLM} message "
        f"and end with a {Role.USER} message. "
        f"Got start role: {data.current_branch[start_idx].role}, "
        f"end role: {data.current_branch[end_idx - 1].role}. "
        "I will adjust by moving the indices inward by one step.\n"
      )
      if data.current_branch[start_idx].role != Role.LLM:
        start_idx += 1
        message += f"Adjusted start_idx to {start_idx}.\n"
      if data.current_branch[end_idx - 1].role != Role.USER:
        end_idx -= 1
        message += f"Adjusted end_idx to {end_idx}.\n"
      assert _validate_indices(start_idx, end_idx, len(data.current_branch)), (
        f"{message}Invalid indices after role adjustment: start_idx={start_idx}, end_idx={end_idx}, current_branch_len={len(data.current_branch)}. "
        "Ensure 0 <= start_idx < end_idx <= current_branch_len."
      )

    # self.context.items[end_idx:-1], take away the last item which is the
    # context modification step itself.
    append_on_top = [
      Message(
        role=Role.USER,
        name="user",
        content=message + "\n" + summary,
        step=data.num_steps,
        traj=data.current_branch_idx,
        task_id=data.current_task_id,
      )
    ] + data.current_branch[end_idx:-1]
    data.branch_at(start_idx - 1)

    for item in append_on_top:
      # This summary message will be numbered start_idx, with role USER
      self.append_and_print(item.role, item.name, item.content, data)

    return

  def _execute_context_command(
    self, cmd: str, data: ContextData
  ) -> NodeOutputType:
    """
    Execute a context command.

    Args:
      cmd (str): the command to execute
      data (ContextData): the context data

      Returns:
        Tuple[Optional["BaseNode"], Optional[ExtraInfo]]: the next node and the extra info
    """
    # Create a dictionary of available tools/objects for the context command
    # For now, only the context object is exposed.
    available_objects = {
      "summarize": lambda start_idx, end_idx, summary: self._summarize(
        start_idx, end_idx, summary, data
      )
    }
    try:
      # Execute the command. Use exec for multi-line statements.
      # The command should be a valid Python expression or statement.
      exec(cmd, {}, available_objects)
    except Exception as e:
      self.append_and_print(
        Role.USER,
        "user",
        f"Context modification command failed with error: {e}",
        data,
      )

    return self.llm_node, None

  def _record(self, data: ContextData) -> NodeOutputType:
    """
    Record a turning point.
    Args:
      data (ContextData): the context data

    Returns:
      Tuple[Optional["BaseNode"], Optional[ExtraInfo]]: the next node and the extra info
    """
    required_patterns = self.console.prompt(
      "write the required commands (separated by comma): "
    )
    forbidden_patterns = self.console.prompt(
      "write the forbidden commands (separated by comma): "
    )
    data.record_turning_point(required_patterns, forbidden_patterns)
    self.console.print(
      f"[bold green]Turning point recorded {data.turning_info}",
      message_type=MessageType.LOG,
    )
    return self, None

  def run(  # type: ignore[override]
    self, data: ContextData, extra_info: Optional[ExtraInfo] = None
  ) -> NodeOutputType:
    # type: ignore[override]
    if isinstance(extra_info, DirectActionExtraInfo):
      action = extra_info.action
      target_step = extra_info.target_step
    elif extra_info is None:
      action, target_step = self._user_input(data)
    else:
      raise ValueError(f"Invalid extra_info: {extra_info} for user action node")
    assert action is not None and target_step is not None, (
      "action and target_step must be provided"
    )

    ret: NodeOutputType
    # if user chooses to feedback
    if action == "f":
      ret = self._feedback(data)

    # if user chooses to edit a step
    if action == "e":
      target_message = data.current_branch[target_step]
      self.console.print(
        f"[bold green]Editing step {target_step}", message_type=MessageType.LOG
      )
      ret = self._edit(target_message, data)

    # if user chooses to resample a step
    if action == "n":
      target_message = data.current_branch[target_step]
      self.console.print(
        f"[bold green]Resampling step {target_step}",
        message_type=MessageType.LOG,
      )
      ret = self._edit(target_message, data, resample=True)

    # if user chooses to record a turning point
    if action == "r":
      self.console.print(
        "[bold green]Recording turning point", message_type=MessageType.LOG
      )
      ret = self._record(data)

    if action == "p":
      if target_step < data.num_steps - 1:
        data.branch_at(target_step)
        self.console.print(
          f"[bold green]Continue from step {target_step}",
          message_type=MessageType.LOG,
        )
      ret = self._proceed(data)
    return ret
